name: bio3d
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.21.0
  - scipy
  - biopython
  - scikit-image
  - matplotlib
  - tk                    
  - igl                   
  - trimesh                
  - networkx            
  - pillow          
  - rtree      
  - shapely
  - openbabel 
  - gemmi    
  - pip
  - pip:
    - pdbe-arpeggio
